--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/hachkingtohach1/ReallyCheat
build-by-default: true
branches:
- master
projects:
  ReallyCheat:
    path: ""
    utils:
      - src: Discord
        version: ^1.0.0
        branch: PM4
...
