name: ReallyCheat
main: hachkingtohach1\reallycheat\RCAPIProvider
author: hachkingtohach1(DragoVN)
api: ["4.0.0", "5.0.0"]
version: PRM-2.1.5
permissions:
  reallycheat.command:
    description: "Permission to use the ReallyCheat command."
    default: false
commands:
  reallycheat:
    permission: reallycheat.command
  rc:
    permission: reallycheat.command
